name: Build and Push Docker Image

# Trigger the workflow when there is a push to the main branch
on:
  push:
    branches:
      - branch  # You can change this to any branch you want

jobs:
  build:
    runs-on: ubuntu-latest  # This tells GitHub Actions to use Ubuntu for the build

    steps:
    # Step 1: Check out the code from your GitHub repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t mamudassirta/testimage:v1 -f test.dockerfile .
    
    # Step 4: Push the Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker push mamudassirta/testimage:v1
